spring.application.name=home-budget-api
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_app
spring.datasource.username=spring_app
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update